/**
 * Pre-generates the grammar parser from src/rmutt.pegjs.
 *
 * Generating at build time rather than on import keeps grammar compilation
 * out of every process start, avoids `__dirname` (incompatible with ESM and
 * bundlers), removes any need to ship the .pegjs file, and lets peggy be a
 * devDependency instead of a runtime one.
 *
 * The emitted parser is typed by a hand-written .d.ts pointing at src/ast.ts,
 * so the rest of the codebase sees the AST union defined in that file.
 */

import peggyModule from 'peggy'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const peggy = peggyModule.default ?? peggyModule
const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const GRAMMAR = join(root, 'src/rmutt.pegjs')
const OUT_DIR = join(root, 'src/generated')

const TYPES = `// Generated by scripts/build-parser.mjs. Do not edit.
import type { Grammar } from '../ast.js';
import type { PeggySyntaxError } from '../errors.js';

export interface ParseOptions {
  grammarSource?: string | undefined;
  startRule?: string | undefined;
}

/** Parses a grammar into the top-level statement list. Throws SyntaxError. */
export function parse(input: string, options?: ParseOptions): Grammar;

export const SyntaxError: {
  new (message: string, expected: unknown, found: unknown, location: unknown): PeggySyntaxError;
};
`

export async function buildParser() {
  const grammar = await readFile(GRAMMAR, 'utf8')
  return peggy.generate(grammar, {
    output: 'source',
    format: 'es',
    grammarSource: 'src/rmutt.pegjs',
  })
}

async function main() {
  const source = await buildParser()

  const banner =
    '// Generated by scripts/build-parser.mjs from src/rmutt.pegjs. Do not edit.\n'

  await mkdir(OUT_DIR, { recursive: true })
  await writeFile(join(OUT_DIR, 'parser.js'), banner + source, 'utf8')
  await writeFile(join(OUT_DIR, 'parser.d.ts'), TYPES, 'utf8')

  // Also emitted straight into dist/: `tsc` compiles .ts only, so a generated
  // .js in src/ would never reach the build output. Writing both here keeps
  // the copy out of the npm script, where it would need a shell and break on
  // Windows.
  await mkdir(join(root, 'dist/generated'), { recursive: true })
  await writeFile(join(root, 'dist/generated/parser.js'), banner + source, 'utf8')

  const kb = (Buffer.byteLength(source) / 1024).toFixed(1)
  console.log(`parser: ${kb} kB -> src/generated/parser.js`)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  await main()
}
