/**
 * Builds the runtime payload.
 *
 * The payload is not a normal build output: its *text* gets inserted into
 * generated code and evaluated with `new Function`. That imposes a contract
 * no ordinary module has: one self-contained expression, no imports, no
 * hoisted helpers. Since the type system can't enforce this, it's asserted here.
 */

import { build } from 'esbuild'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** The name the bundle binds itself to. Generated code refers to it. */
export const PAYLOAD_GLOBAL = '$rmutt'

// Things that cannot resolve inside `new Function`
const FORBIDDEN = [
  [/\brequire\s*\(/, 'a `require(` call'],
  [/^\s*import\s/m, 'a top-level `import` statement'],
  [/\bfrom\s+["']node:/, 'a `node:` builtin import'],
  [/\bprocess\.(?:env|argv|cwd)\b/, 'a reference to `process`'],
]

export function assertSelfContained(source) {
  for (const [pattern, description] of FORBIDDEN) {
    const match = pattern.exec(source)
    if (match) {
      const line = source.slice(0, match.index).split('\n').length
      throw new Error(
        `Runtime payload is not self-contained: found ${description} at line ${line}.\n` +
          `  ${match[0].trim()}\n` +
          `The payload is injected into generated code and run through \`new Function\`, ` +
          `where none of these resolve. Check tsconfig.payload.json and the esbuild target.`,
      )
    }
  }

  // Evaluate the payload just like the generated code will: inside `new Function`
  // with no ambient scope, and confirm the shape codegen depends on.
  let exported
  try {
    // oxlint-disable-next-line no-implied-eval
    exported = new Function(`${source}\nreturn ${PAYLOAD_GLOBAL};`)()
  } catch (err) {
    throw new Error(
      `Runtime payload does not evaluate inside \`new Function\`: ${err.message}\n`,
    )
  }

  for (const name of ['Random', 'createRuntime']) {
    if (typeof exported?.[name] !== 'function') {
      throw new Error(
        `Runtime payload evaluated, but \`${PAYLOAD_GLOBAL}.${name}\` is ` +
          `${typeof exported?.[name]}, not a function. Codegen depends on it.`,
      )
    }
  }
}

/** Renders `source` as a JS template-literal string that evaluates back to it. */
function toTemplateLiteral(source) {
  const escaped = source
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
  return '`' + escaped + '`'
}

export async function buildPayload() {
  const result = await build({
    entryPoints: [join(root, 'src/payload/index.ts')],
    bundle: true,
    format: 'iife',
    globalName: PAYLOAD_GLOBAL,
    platform: 'neutral',
    target: 'es2022',
    write: false,
    legalComments: 'none',
  })

  const source = result.outputFiles[0].text
  assertSelfContained(source)
  return source
}

async function main() {
  const source = await buildPayload()

  // Embedded as a string constant that codegen injects into generated expanders.
  await mkdir(join(root, 'src/generated'), { recursive: true })
  await writeFile(
    join(root, 'src/generated/payload.ts'),
    '// Generated by scripts/build-payload.mjs. Do not edit.\n' +
      `export const PAYLOAD_GLOBAL = ${JSON.stringify(PAYLOAD_GLOBAL)};\n` +
      `export const PAYLOAD_SOURCE = ${toTemplateLiteral(source)};\n`,
    'utf8',
  )

  const kb = (Buffer.byteLength(source) / 1024).toFixed(1)
  console.log(`payload: ${kb} kB -> src/generated/payload.ts`)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  await main()
}
